version: "3.9"

services:
  backend:
    build: ./be_simple_crud
    container_name: backend_flask
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app-network
    environment:
      JWT_SECRET: mysecretjwt
      DB_HOST: database
      DB_DATABASE: horus_surya_db
      DB_USERNAME: surya
      DB_PASSWORD: surya123
  
  frontend:
    build: ./simple_crud
    container_name: frontend_vue
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: horus_surya_db
      MYSQL_USER: surya
      MYSQL_PASSWORD: surya123

networks:
  app-network:
    driver: bridge