version: "3.9"

services:
  backend:
    build: ./be_simple_crud
    container_name: backend_flask
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app-network
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  
  frontend:
    build: ./simple_crud
    container_name: frontend_vue
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  app-network:
    driver: bridge